apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: tmirtdockerhub/test:9
        name: flaskdemo
        imagePullPolicy: Always
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "99.124.229.98/32"
    - "34.209.200.225/32"
    - "52.38.231.38/32"
    - "70.118.93.138/32"
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
